name: Commit Notice Injection

on:
  push:
    branches: 
      - master
    paths:
      - "img/19/**"
      - "img/20/**"
      
jobs:
  build:
    name: Jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twitter

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          echo ::set-env name=ADDED_FILES::${{ steps.files.outputs.added_modified }}
          
      - name: Hello Script Mode
        env:
          GITHUB_TOKEN:                 ${{ secrets.GITHUB_TOKEN }}
          TWITTER_API_KEY:              ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY:       ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN:         ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET:  ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          msg_A: "https://log.kmwtr.xyz"
        run: |
          python .github/actions/commit_notice_injector.py
